@url = http://0.0.0.0:3000

###
GET {{url}}/all

###
# neveikia. Kodėl?
PUT {{url}}/person
content-type: application/json

{
    "firstName": "Jonas",
    "lastName": "Petraitis",
    "id": 2
}

###


###
PUT {{url}}/person
Content-Type: application/x-www-form-urlencoded

firstName=Jonas
&lastName=Petraitis
&id=2

###
PUT {{url}}/person
Content-Type: application/x-www-form-urlencoded

firstName=User3fn
&lastName=User3ln
&id=3